<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $permissions = [
            [
                'module_id'     => 1,
                'sub_module_id' => 1,
                'label'         => 'Home',
                'name'          => 'web.home',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 1,
                'sub_module_id' => 2,
                'label'         => 'About Us',
                'name'          => 'web.about.us',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 1,
                'sub_module_id' => 3,
                'label'         => 'Contact Us',
                'name'          => 'web.contact.us',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 1,
                'sub_module_id' => 4,
                'label'         => 'Terms & Conditions',
                'name'          => 'web.terms.conditions',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 1,
                'sub_module_id' => 5,
                'label'         => 'Privacy Policy',
                'name'          => 'web.privacy.policy',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 1,
                'sub_module_id' => 6,
                'label'         => 'Cookies Policy',
                'name'          => 'web.cookies.policy',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 1,
                'sub_module_id' => 7,
                'label'         => 'Site Map',
                'name'          => 'web.site.map',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Login',
                'name'          => 'login',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Login Submit',
                'name'          => 'login.submit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Register',
                'name'          => 'register',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Register Submit',
                'name'          => 'register.submit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Logout',
                'name'          => 'logout',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Verify Email',
                'name'          => 'verification.notice',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Verify Email Submit',
                'name'          => 'verification.verify',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Forgot Password',
                'name'          => 'password.request',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Forgot Password Submit',
                'name'          => 'password.email',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Reset Password',
                'name'          => 'password.reset',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 13,
                'label'         => 'Reset Password Submit',
                'name'          => 'password.update',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 19,
                'label'         => 'Profile',
                'name'          => 'panel.profile',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 2,
                'sub_module_id' => 19,
                'label'         => 'Profile Update',
                'name'          => 'panel.profile.submit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 14,
                'label'         => 'Role List',
                'name'          => 'panel.roles.index',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 14,
                'label'         => 'Create Role',
                'name'          => 'panel.roles.create',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 14,
                'label'         => 'Show Role',
                'name'          => 'panel.roles.show',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 14,
                'label'         => 'Save Role',
                'name'          => 'panel.roles.store',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 14,
                'label'         => 'Edit Role',
                'name'          => 'panel.roles.edit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 14,
                'label'         => 'Update Role',
                'name'          => 'panel.roles.update',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 14,
                'label'         => 'Delete Role',
                'name'          => 'panel.roles.destroy',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 15,
                'label'         => 'User List',
                'name'          => 'panel.users.index',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 15,
                'label'         => 'Create User',
                'name'          => 'panel.users.create',
                'status'        => 3,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 15,
                'label'         => 'Show User',
                'name'          => 'panel.users.show',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 15,
                'label'         => 'Save User',
                'name'          => 'panel.users.store',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 15,
                'label'         => 'Edit User',
                'name'          => 'panel.users.edit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 15,
                'label'         => 'Update User',
                'name'          => 'panel.users.update',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 15,
                'label'         => 'Delete User',
                'name'          => 'panel.users.destroy',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 16,
                'label'         => 'Module List',
                'name'          => 'panel.modules.index',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 16,
                'label'         => 'Create Module',
                'name'          => 'panel.modules.create',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 16,
                'label'         => 'Show Module',
                'name'          => 'panel.modules.show',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 16,
                'label'         => 'Save Module',
                'name'          => 'panel.modules.store',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 16,
                'label'         => 'Edit Module',
                'name'          => 'panel.modules.edit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 16,
                'label'         => 'Update Module',
                'name'          => 'panel.modules.update',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 16,
                'label'         => 'Delete Module',
                'name'          => 'panel.modules.destroy',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 17,
                'label'         => 'Submodule List',
                'name'          => 'panel.sub-modules.index',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 17,
                'label'         => 'Create Submodule',
                'name'          => 'panel.sub-modules.create',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 17,
                'label'         => 'Show Submodule',
                'name'          => 'panel.sub-modules.show',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 17,
                'label'         => 'Save Submodule',
                'name'          => 'panel.sub-modules.store',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 17,
                'label'         => 'Edit Submodule',
                'name'          => 'panel.sub-modules.edit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 17,
                'label'         => 'Update Submodule',
                'name'          => 'panel.sub-modules.update',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 17,
                'label'         => 'Delete Submodule',
                'name'          => 'panel.sub-modules.destroy',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 18,
                'label'         => 'Permission List',
                'name'          => 'panel.permissions.index',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 18,
                'label'         => 'Create Permission',
                'name'          => 'panel.permissions.create',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 18,
                'label'         => 'Show Permission',
                'name'          => 'panel.permissions.show',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 18,
                'label'         => 'Save Permission',
                'name'          => 'panel.permissions.store',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 18,
                'label'         => 'Edit Permission',
                'name'          => 'panel.permissions.edit',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 18,
                'label'         => 'Update Permission',
                'name'          => 'panel.permissions.update',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 3,
                'sub_module_id' => 18,
                'label'         => 'Delete Permission',
                'name'          => 'panel.permissions.destroy',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
            [
                'module_id'     => 4,
                'sub_module_id' => 20,
                'label'         => 'Dashboard',
                'name'          => 'panel.home',
                'status'        => 1,
                'created_at'    => '2025-06-02 21:46:10',
                'updated_at'    => '2025-06-02 21:46:10',
            ],
        ];

        Permission::insert($permissions);
    }
}
